

/* Create Tables */

-- twitterのuserを保存します。
CREATE TABLE USERS
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id : user id',
	NAME VARCHAR(20) NOT NULL COMMENT 'アカウント名(ユニーク)',
	EMAIL VARCHAR(255) NOT NULL COMMENT 'メールアドレス',
	PASSWORD VARCHAR(255) NOT NULL COMMENT 'パスワード',
	DISPLAY_NAME VARCHAR(20) NOT NULL COMMENT '表示名',
	CREATED_AT DATETIME NOT NULL COMMENT '作成した時のタイムスタンプ',
	UPDATED_AT DATETIME NOT NULL COMMENT '最終更新時のタイムスタンプ',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'ユーザー : twitterのuserを保存します。';



/* Create Indexes */

CREATE UNIQUE INDEX UQ_USERS_NAME USING BTREE ON USERS (NAME ASC);
CREATE UNIQUE INDEX UQ_USERS_EMAIL USING BTREE ON USERS (EMAIL ASC);



