

/* Create Tables */

-- twitterのuserを保存します。
CREATE TABLE USERS
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id : user id',
	UQ_USERS_NAME VARCHAR(20) NOT NULL UNIQUE COMMENT 'uq_users_name',
	UQ_USERS_EMAIL VARCHAR(255) NOT NULL UNIQUE COMMENT 'uq_users_email',
	PASSWORD VARCHAR(255) NOT NULL COMMENT 'password',
	DISPLAY_NAME VARCHAR(20) NOT NULL COMMENT 'display_name',
	CREATED_AT DATETIME NOT NULL COMMENT 'created_at',
	UPDATED_AT DATETIME NOT NULL COMMENT 'updated_at',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'NEW_TABLE : twitterのuserを保存します。';



