

/* Create Tables */

-- フォロー関係
CREATE TABLE FOLLOWS
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	FOLLOWER BIGINT NOT NULL COMMENT 'フォローしている人 : user id',
	FOLLOWEE BIGINT NOT NULL COMMENT 'フォローされている人 : user id',
	CREATED_AT DATETIME NOT NULL COMMENT '作成した時のタイムスタンプ',
	UPDATED_AT DATETIME NOT NULL COMMENT '最終更新時のタイムスタンプ',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'フォロー関係 : フォロー関係';


-- tweet本体
CREATE TABLE TWEETS
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id',
	USER_ID BIGINT NOT NULL COMMENT '投稿主 : user id',
	CONTENT VARCHAR(140) NOT NULL COMMENT '本文',
	CREATED_AT DATETIME NOT NULL COMMENT '作成した時のタイムスタンプ',
	UPDATED_AT DATETIME NOT NULL COMMENT '最終更新時のタイムスタンプ',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'ツイート : tweet本体';


-- twitterのuserを保存します。
-- ツイートした日時はcreated_atで管理する。
CREATE TABLE USERS
(
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'id : user id',
	NAME VARCHAR(255) NOT NULL COMMENT '名前',
	EMAIL VARCHAR(255) NOT NULL COMMENT 'メールアドレス',
	PASSWORD VARCHAR(255) NOT NULL COMMENT 'パスワード',
	DISPLAY_NAME VARCHAR(20) NOT NULL COMMENT '表示名',
	CREATED_AT DATETIME NOT NULL COMMENT '作成した時のタイムスタンプ',
	UPDATED_AT DATETIME NOT NULL COMMENT '最終更新時のタイムスタンプ',
	PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = 'ユーザー : twitterのuserを保存します。
ツイートした日時はcreated_atで管理する。';



/* Create Indexes */

-- 同一のフォロワーとフォロウィーの関係は一つであるべき
CREATE UNIQUE INDEX UQ_FOLLOWS_RELATION USING BTREE ON FOLLOWS (FOLLOWER ASC, FOLLOWEE ASC);
CREATE UNIQUE INDEX UQ_USERS_NAME USING BTREE ON USERS (NAME ASC);
CREATE UNIQUE INDEX UQ_USERS_EMAIL USING BTREE ON USERS (EMAIL ASC);



/* Create Foreign Keys */

ALTER TABLE FOLLOWS
	ADD CONSTRAINT FK_FOLLOWS_FOLLOWER FOREIGN KEY (FOLLOWER)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FOLLOWS
	ADD CONSTRAINT FK_FOLLOWS_FOLLOWEE FOREIGN KEY (FOLLOWEE)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEETS
	ADD CONSTRAINT FK_TWEETS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



